name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: 'aiherrera'
          BLOG_URL: 'https://blog.aiherrera.com'
          COUNT: 5
          STYLE: 'blog-alternate'
          FILE: "README.md"
          USE_CANONICAL_URL: "true"
          USE_CUSTOM_BLOG_URL: "true"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
